---
version: '3'

tasks:
  default:
    cmds:
      - task -l

  build:
    desc: Build the project for all supported architectures (requires cross)
    cmds:
      - task: build-amd64
      - task: build-arm64
      - task: build-armv7
      - task: build-armv6

  build-amd64:
    desc: Build for AMD64 (x86_64)
    cmds:
      - cross build --release --target x86_64-unknown-linux-gnu

  build-arm64:
    desc: Build for ARM64 (aarch64)
    cmds:
      - cross build --release --target aarch64-unknown-linux-gnu

  build-armv7:
    desc: Build for ARMv7
    cmds:
      - cross build --release --target armv7-unknown-linux-gnueabihf

  build-armv6:
    desc: Build for ARMv6
    cmds:
      - cross build --release --target arm-unknown-linux-gnueabihf

  build-local:
    desc: Build the project in release mode for the current architecture
    cmds:
      - cargo build --release

  build-debug:
    desc: Build the project in debug mode
    cmds:
      - cargo build

  run:
    desc: Run the project (requires arguments or env vars, runs help by default)
    cmds:
      - cargo run -- --help

  check:
    desc: Check code for errors without generating binary
    cmds:
      - cargo check

  test:
    desc: Run all tests
    cmds:
      - cargo test

  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt

  lint:
    desc: Lint code with clippy
    cmds:
      - cargo clippy -- -D warnings

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean