import sys

def fix_tests():
    path = 'src/tests.rs'
    with open(path, 'r') as f:
        content = f.read()

    mappings = {
        "start_vm": "vm_power_action",
        "stop_vm": "vm_power_action",
        "shutdown_vm": "vm_power_action",
        "reboot_vm": "vm_power_action",
        "reset_vm": "vm_power_action",
        "start_container": "vm_power_action",
        "stop_container": "vm_power_action",
        "shutdown_container": "vm_power_action",
        "reset_container": "vm_power_action",
        "create_vm": "manage_resource",
        "delete_vm": "manage_resource",
        "create_container": "manage_resource",
        "delete_container": "manage_resource",
        "clone_vm": "manage_resource",
        "migrate_vm": "manage_resource",
        "template_vm": "manage_resource",
        "update_vm_resources": "manage_resource_config",
        "update_container_resources": "manage_resource_config",
        "add_disk": "manage_resource_config",
        "remove_disk": "manage_resource_config",
        "add_network": "manage_resource_config",
        "remove_network": "manage_resource_config",
        "set_vm_cloudinit": "manage_resource_config",
        "add_lxc_bind_mount": "manage_resource_config",
        "add_lxc_mountpoint": "manage_resource_config",
        "remove_lxc_mountpoint": "manage_resource_config",
        "add_pci_device": "manage_resource_config",
        "add_usb_device": "manage_resource_config",
        "remove_vm_device": "manage_resource_config",
        "vm_exec": "manage_resource_config",
        "snapshot_vm": "manage_snapshot_backup",
        "rollback_vm": "manage_snapshot_backup",
        "delete_snapshot": "manage_snapshot_backup",
        "create_backup": "manage_snapshot_backup",
        "restore_backup": "manage_snapshot_backup",
        "create_backup_schedule": "manage_snapshot_backup",
        "update_backup_schedule": "manage_snapshot_backup",
        "delete_backup_schedule": "manage_snapshot_backup",
        "manage_service": "manage_node_system",
        "run_apt_update": "manage_node_system",
        "add_repository": "manage_node_system",
        "update_repository_state": "manage_node_system",
        "upload_certificate": "manage_node_system",
        "generate_acme_certificate": "manage_node_system",
        "set_subscription_key": "manage_node_system",
        "add_storage": "manage_cluster_config",
        "update_storage": "manage_cluster_config",
        "delete_storage": "manage_cluster_config",
        "create_sdn_zone": "manage_cluster_config",
        "delete_sdn_zone": "manage_cluster_config",
        "create_sdn_vnet": "manage_cluster_config",
        "delete_sdn_vnet": "manage_cluster_config",
        "create_firewall_alias": "manage_cluster_config",
        "update_firewall_alias": "manage_cluster_config",
        "delete_firewall_alias": "manage_cluster_config",
        "create_security_group": "manage_cluster_config",
        "delete_security_group": "manage_cluster_config",
        "add_security_group_rule": "manage_cluster_config",
        "create_pool": "manage_cluster_config",
        "update_pool": "manage_cluster_config",
        "delete_pool": "manage_cluster_config",
        "create_role": "manage_cluster_config",
        "update_role": "manage_cluster_config",
        "delete_role": "manage_cluster_config",
        "update_acl": "manage_cluster_config",
        "create_replication_job": "manage_cluster_config",
        "update_replication_job": "manage_cluster_config",
        "delete_replication_job": "manage_cluster_config",
        "add_ha_resource": "manage_cluster_config",
        "update_ha_resource": "manage_cluster_config",
        "remove_ha_resource": "manage_cluster_config",
        "create_pci_mapping": "manage_cluster_config",
        "update_pci_mapping": "manage_cluster_config",
        "delete_pci_mapping": "manage_cluster_config",
        "create_usb_mapping": "manage_cluster_config",
        "update_usb_mapping": "manage_cluster_config",
        "delete_usb_mapping": "manage_cluster_config",
        "create_metric_server": "manage_cluster_config",
        "update_metric_server": "manage_cluster_config",
        "delete_metric_server": "manage_cluster_config",
        "create_ceph_pool": "manage_cluster_config",
        "delete_ceph_pool": "manage_cluster_config",
        "delete_storage_content": "manage_cluster_config",
        "create_user": "manage_cluster_config",
        "add_tag": "manage_tags",
        "remove_tag": "manage_tags",
        "set_tags": "manage_tags",
    }

    for old, new in mappings.items():
        content = content.replace(f'"{old}"', f'"{new}"')

    with open(path, 'w') as f:
        f.write(content)

if __name__ == "__main__":
    fix_tests()
